export const SITE_AUTHOR = "José David Hernández Hortúa";
export const SITE_NAME = "JoséDHernández";
export const SITE_DESCRIPTION =
  "Desarrollo web FullStack e ingeniero de software en formación, centrado en la experiencia de usuario (UX) y diseño de interfaces (UI).";
export const SITE_KEYWORDS = [
  "José David Hernández Hortúa",
  "Ingeniero de Software",
  "Portafolio de desarrollo",
  "Desarrollador FullStack",
  "Desarrollador web",
  "Aplicaciones web",
  "Desarrollo de software",
  "FrontEnd",
  "BackEnd",
  "JavaScript",
  "TypeScript",
  "React",
  "Astro",
  "Node.js",
  "Express.js",
  "MongoDB",
  "MySQL",
  "SQL",
  "APIs REST",
  "WebSockets",
  "HTML",
  "CSS",
  "SASS",
  "Bootstrap",
  "Tailwind CSS",
  "Git",
  "GitHub",
  "Diseño de interfaces",
  "UI",
  "UX",
  "Experiencia de usuario",
  "Accesibilidad web",
  "Responsive design",
  "Desarrollador colombiano",
  "Proyectos académicos",
  "Portafolio web",
  "Software educativo",
  "José David Hernández",
  "José Hernández",
  "JoseDHernandez",
  "josedhernandez",
  "José David H.",
  "José D. Hernández",
  "jose david hernandez hortua",
  "josedhernandez.com",
  "portafolio José Hernández",
  "José Hernández FullStack",
  "proyectos de programación",
  "desarrollador junior",
  "ingeniería de software",
  "portafolio profesional",
  "CineFan",
  "cartas contra la humanidad",
  "Cards Against Humanity",
  "versión web de Cards Against Humanity",
  "CCH",
  "RACCB",
  "La cueva de Ana",
  "Fanpage del Cuarteto de Nos",
  "fanpage Cuarteto de Nos",
  "Sea Battle",
  "juego Sea Battle",
  "juego Batalla Naval",
  "portafolio desarrollador fullstack",
  "desarrollador web junior Colombia",
  "ingeniero de software",
  "aplicaciones web con React y Node.js",
  "MongoDB, MySQL, JavaScript",
  "Tailwind CSS, SASS, Bootstrap",
  "proyectos de programación",
  "experiencia de usuario (UX)",
  "responsive design",
  "accesibilidad web",
  "portafolio José Hernández",
  "CineFan, Sea Battle, Cartas Contra la Humanidad",
  "desarrollador freelance Colombia",
  "josedhernandez.com",
].join(", ");
